{% set name = "Quart-Trio" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 76617d2651ab42824ff8ee53a7bde8e482a8543aac4381f8333f8e97ca90f46f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - quart >=0.23
    - trio >=0.19.0
    - hypercorn >=0.12.0
    - exceptiongroup >=1.1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - quart_trio

about:
  home: https://gitlab.com/pgjones/quart-trio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Quart-Trio is an extension for Quart to support the Trio event loop
  description: |
    Quart-Trio is an extension for Quart to support the Trio event loop.
    This is an alternative to using the asyncio event loop present in the Python
    standard library and supported by default in Quart.

extra:
  recipe-maintainers:
    - dhirschfeld
    - scopatz
